resource.go, testdata/output/2021-06-01/spec.json, testdata/output/2021-06-01/spec.yaml, testdata/output/2021-06-01~beta/spec.json, testdata/output/2021-06-01~beta/spec.yaml, testdata/output/2021-06-01~experimental/spec.json, testdata/output/2021-06-01~experimental/spec.yaml, testdata/output/2021-06-04/spec.json, testdata/output/2021-06-04/spec.yaml, testdata/output/2021-06-04~beta/spec.json, testdata/output/2021-06-04~beta/spec.yaml, testdata/output/2021-06-04~experimental/spec.json, testdata/output/2021-06-04~experimental/spec.yaml, testdata/output/2021-06-07/spec.json, testdata/output/2021-06-07/spec.yaml, testdata/output/2021-06-07~beta/spec.json, testdata/output/2021-06-07~beta/spec.yaml, testdata/output/2021-06-07~experimental/spec.json, testdata/output/2021-06-07~experimental/spec.yaml, testdata/output/2021-06-13/spec.json, testdata/output/2021-06-13/spec.yaml, testdata/output/2021-06-13~beta/spec.json, testdata/output/2021-06-13~beta/spec.yaml, testdata/output/2021-06-13~experimental/spec.json, testdata/output/2021-06-13~experimental/spec.yaml
Add additional metadata to the compiled OpenAPI output indicating which
resource a given path comes from.
This is helpful for linking the compiled output back to the source, as
well as version lifecycle analysis.
=> feat: add x-snyk-api-resource extension to compiled path info

.circleci/config.yml, .golangci.yml, Makefile, cmd/compiler_test.go, cmd/localize.go, cmd/resolve.go, cmd/scaffold.go, cmd/scaffold_test.go, cmd/version.go, cmd/version_test.go, config/config_test.go, document.go, include_headers.go, internal/compiler/compiler.go, internal/compiler/compiler_test.go, internal/generator/generator.go, internal/generator/generator_test.go, internal/scaffold/manifest_test.go, internal/scaffold/scaffold.go, internal/scaffold/scaffold_test.go, internal/spectral/linter.go, internal/sweatercomb/linter.go, internal/sweatercomb/linter_test.go, localizer_test.go, merge_test.go, version.go, version_test.go
Add Makefile target and CircleCI job for running golangci-lint.
Fixed dead code, uncaught errors, and style issues flagged by linter.
Drive-by: VersionSlice.Resolve:
- Returning a copy of the matched value
- Added a test case
=> chore: introduce golangci-lint

go.mod, go.sum, resource.go, resource_test.go, spec_test.go
Adds 3 utility functions for downstream clients to validate when using `ExtensionString` to check compiled vervet specification documents. 
* One for the stability extension
* One for the version extension
* And a generic so that the logic doesn't have to be repeated.
=> feat: add extension not found utility functions

spec_test.go, version.go, version_test.go
Adding MustParseVersion and MustParseStability for convenience when
initializing global vars, tests, etc.
=> chore: MustParse... methods

cmd/cmd.go, cmd/scaffold.go, cmd/scaffold_test.go, cmd/version.go, cmd/version_test.go
The version command currently requires API and resource to be specified at
invocation. It would be better if the command interactively prompted for those
values if they were omitted by the user.
Fixes #57
=> feat: adds interactive prompting to version new cmd

go.sum, internal/compiler/compiler.go, internal/optic/files.go, internal/optic/linter.go, internal/optic/linter_test.go
Arrange the Docker volume mounts to correctly reference the "from" and
"to" specs such that relative $refs resolve correctly.
=> fix: optic-ci compare with correct mount paths

internal/linter/optic/context.go, internal/linter/optic/linter.go, internal/linter/optic/linter_test.go, version.go
In order for optic-ci to evaluate versioning lifecycle rules, some
external information needs to be provided, telling optic:
* When a proposed change would occur
* The resource and version being changed
* Existing versions in the API that may deprecate the version under
change.
=> fix: provide optic-ci with context

config/api.go, config/config_test.go, config/linter.go
Optic rules are not currently applied to the compiled output stage and
this is not yet supported, lacking a clear use case or definition.
Optic rules are also not allowed for "overrides". Linter overrides
were a stop-gap measure that should be better solved with a more
well-defined standards & compliance lifecycle.
Add some additional config sanity checks.
=> fix: restrict optic configuration to supported functionality

resource.go, testdata/output/2021-06-01~experimental/spec.json, testdata/output/2021-06-01~experimental/spec.yaml, testdata/output/2021-06-04~experimental/spec.json, testdata/output/2021-06-04~experimental/spec.yaml, testdata/output/2021-06-07~experimental/spec.json, testdata/output/2021-06-07~experimental/spec.yaml, testdata/output/2021-06-13~beta/spec.json, testdata/output/2021-06-13~beta/spec.yaml, testdata/output/2021-06-13~experimental/spec.json, testdata/output/2021-06-13~experimental/spec.yaml, version.go, version_test.go
Annotate paths in a given resource version with the newer release
version that deprecates it, and when the deprecated version may be
sunset.
This may be used in linting, middleware, and documentation.
Implements #86.
Stacked on #89.
=> feat: add version deprecation and sunset eligibility

merge.go, merge_test.go, testdata/merge_test_dst_missing_components.yaml
openapi3 sets the zero value of its schema objects to uninitialized
maps. This is generally fine when loading a spec, as that process
initializes the map, but when we merge items in vervet if a component
had no data in the initial spec the component map remains unitialized,
causing a panic in `Merge` when we attempt to write to it.
To address this, we check at merge time if the src component map is
initialized (not nil) and if the destination map is not. If that's the
case, we call `make` to set the map to a non nil value.
=> fix: ensures destination components exist in merge

internal/files/files.go, internal/linter/optic/git.go, internal/linter/optic/linter.go, internal/linter/optic/linter_test.go
This updates the optic linter to use the bulk-compare command introduced
in https://github.com/snyk/sweater-comb/pull/107.
=> feat: support optic bulk compare

internal/linter/optic/linter.go
There were a couple of log messages leftover from debugging the optic
linter.
=> chore: remove unnecessary log messages

config/linter.go, internal/linter/optic/linter.go
This removes a lot of redundant volume mounts from the docker command line and adds a debug logging option to help with figuring out what vervet is actually running on `vervet lint`.
=> chore: optimize optic docker cmdline, add debug logging

versionware/handler.go, versionware/handler_test.go
Add a multiplexing handler that dispatches requests to handlers based on
a version query parameter.
=> feat: versionware; introduce version-based routing

merge.go, merge_test.go
This fixes a panicking nil map deref when merging into an empty
openapi3.T destination.
This fixes an intermittent panic in VU tests I've seen in CircleCI:
```
?   	vervet-underground	[no test files]
?   	vervet-underground/config	[no test files]
{"level":"error","error":"no matching version","time":"2021-12-16T23:01:11Z","message":"Could not resolve for service http://127.0.0.1:40771 version 2021-09-01"}
{"level":"error","error":"no matching version","time":"2021-12-16T23:01:11Z","message":"Could not resolve for service http://127.0.0.1:40771 version 2021-09-16"}
--- FAIL: TestScraper (0.08s)
panic: assignment to entry in nil map [recovered]
panic: assignment to entry in nil map
goroutine 19 [running]:
testing.tRunner.func1.2(0xb45860, 0xc774f0)
/usr/local/go/src/testing/testing.go:1143 …
```
=> fix: empty merge destination

.circleci/config.yml, scripts/dist.bash
To avoid burning through more major versions, setting releaser to
--dry-run until we can trust it.
This way we can see what it would do in CI logs.
=> chore: set semantic-releaser to dry-run

.circleci/config.yml, vervet-underground/Dockerfile
The working directory alone does not change to the subdirectory build in CircleCI.
Fix changing working directory to use `vervet-underground` directory appropriately.
=> chore: fix working dir start point dockerfile

internal/linter/optic/linter_test.go
A test was failing depending on the value of TMPDIR. This updates the
expected value to use a platform/TMPDIR-invariant path prefix.
=> fix: tmpdir-dependent test failure

cmd/resolve.go, cmd/version.go, cmd/version_test.go, internal/compiler/compiler.go, resource.go, resource_test.go, resource_versions.go, spec.go, spec_test.go, testdata/output/2021-06-01~experimental/spec.json, testdata/output/2021-06-01~experimental/spec.yaml, testdata/output/2021-06-04~experimental/spec.yaml, testdata/output/2021-06-07~experimental/spec.json, testdata/output/2021-06-13~beta/spec.json, testdata/output/2021-06-13~beta/spec.yaml, testdata/output/2021-06-13~experimental/spec.json, testdata/output/2021-06-13~experimental/spec.yaml, testdata/output/2021-08-20~beta/spec.json, testdata/output/2021-08-20~beta/spec.yaml, testdata/output/2021-08-20~experimental/spec.json, testdata/output/2021-08-20~experimental/spec.yaml, testdata/output/embed.go, testdata/resources/projects/2021-08-20/spec.yaml
Fixes #99, ~~#100~~ (see note below).
This changes how operation (path + method) are resolved and merged
across spec versions within a stability level.
Operations are now cumulative. Unless a particular operation (path +
method) is redefined or explicitly deprecated, past releases are assumed
to carry over to newer versions.
BREAKING CHANGE: This changes the behavior of the compiler and resulting
output. It's also a breaking API change, requiring a major version bump.
We do not anticipate any breaking changes to OpenAPI consumers.
=> feat: per-operation versioning and deprecation

.circleci/config.yml, scripts/dist.bash, scripts/release.bash
Using ccv to derive a release version from conventional commit comments. Tagging, NPM-ing, and Github releasing from that if unreleased, on landing into main.
=> fix: auto-release on landing into main

Makefile, internal/compiler/compiler.go, testdata/output/embed.go, versionware/example/chi/example_test.go, versionware/example/embed_test.go, versionware/example/go.mod, versionware/example/gorilla/example_test.go, versionware/example/releases/embed.go, versionware/example/resources/things/2021-11-01/handlers.go, versionware/example/resources/things/2021-11-08/handlers.go, versionware/example/resources/things/2021-11-20/handlers.go
This fixes gofmt and adds a godoc comment to the generated embed.go
which embeds the compiled OpenAPI specs for compilation into a Go
service.
Added a test to assert that the godoc comment does not interfere with
the //go:embed magic comments.
Added golangci-lint to the versionware examples and cleaned a few things
up.
Fixes #120.
=> fix: add godoc comment to generated embed.FS

config/config_test.go, config/linter.go, internal/linter/optic/linter.go, internal/linter/optic/linter_test.go
Fix comparison paths to work with the volume mounts used when Optic CI
is run as a Docker image.
Update the default Docker image used by the Optic CI linter to the
latest official release on Docker Hub,
https://hub.docker.com/r/snyk/sweater-comb.
=> fix: running optic linter from docker

versionware/example/go.mod, versionware/example/go.sum, versionware/validator.go, versionware/validator_test.go
Go's net/url.Parse is very permissive. It's easy to pass the same
"host:port" used to configure the listener as the server URL, which gets
mis-interpreted as host://port, when http://host:port was intended.
This adds strict validation to the server URL, preventing this kind of
subtle bug from creating much confusion when the validator then fails to
match any paths and everything 404s.
=> fix: validate the server URL to prevent subtle parsing effects

versionware/export_test.go, versionware/validator.go, versionware/validator_test.go
Respond 400 when a version date is requested from the future.
=> fix: disallow requesting API version dates in the future

versionware/validator.go, versionware/validator_test.go
If an empty array of specs is passed to versionware.NewValidator, all
requests will 404. This is definitely not what callers will expect or
want.
=> fix: fail fast when creating a validator that has no specs.

cmd/version.go, cmd/version_test.go
When running `vervet version list <api> <resource>`, endpoint versions
were not being filtered by the given resource, when given.
=> fix: version list resource filtering

mkdocs.yml
The leading docs/ needed to be removed from the generated documentation
paths.
=> fix: correct techdocs paths

packaging/npm/package.json.in, scripts/dist.bash
Add a darwin arm64 binary to the multi-arch NPM binary package.
$ file dist/bin/vervet-darwin-arm64
dist/bin/vervet-darwin-arm64: Mach-O 64-bit executable arm64
Fixes #134
=> feat: support macOS on M1

document.go, go.mod, go.sum
When processing OpenAPI specs that contain a large number of http $refs,
vervet performance becomes unbearably slow. This is caused by overly
simplistic URI resolution in kin-openapi. Solution is a fix upstream in
https://github.com/getkin/kin-openapi/pull/469. Until that lands, vervet
may use a go.mod replace directive to obtain the fix.
Drive-by: simplify implementation of Document.LoadReference, which was
changing the current working directory unnecessarily in order to process
relative paths.
=> fix: performance issues due to http $refs

.gitignore, Makefile, cmd/cmd.go, scripts/dist.bash, scripts/genversion.bash, scripts/release.bash
urfave provides version info automatically as part of the cli app setup,
provided the cli is given "Version" as part of its setup.
This sets that field based on a global var in the `cmd` package, which can be
set via the ldflags arg at build time, e.g. to set the version based on git
tag as done in the Makefile.
=> feat: adds vervet's version info to cli

go.mod, go.sum, versionware/example/go.mod, versionware/example/go.sum
This updates vervet with the latest kin-openapi, which includes HTTP URI
$ref caching (https://github.com/getkin/kin-openapi/pull/469).
It also drops the replace go.mod directive, which should restore `go
install`ability of vervet.
=> fix: upgrade kin-openapi to 0.90.0

packaging/npm/passthrough.js, scripts/dist.bash
* switch name of output binaries to match node arch convention
* add linux arm64 build
* use process.arch to select correct bin
=> fix: select correct architecture

cmd/resolve.go, resource.go, version.go, version_test.go, versionware/handler.go, versionware/validator.go
My main goal with this PR is to permit chaining method calls on Version objects like:
```go
vstr := MustParseVersion("v1").AddDays(2).String()
```
This is currently not possible with some of the methods (e.g. `DateString`, `String`, `Add`, `Compare`, ...) because they are defined as pointer method.
`Version` is a relatively small structure composed of an `int`, an `int64`, a `uint64` and an address. Passing it by values, in similar way that it is done for `time.Time` seems appropriate (https://github.com/golang/go/blob/40e24a942bce7b10e23a7282e673ac8a758ca378/src/time/time.go#L248).
I took the PR a step further by updating the definition of `ParseVersion` to return a `Version` instead of a pointer to it. This is a breaking change that we may want to avoid. Looking for your inputs here. …
=> feat: Make vervet.Version take in parameters by value

internal/cmd/generate.go, internal/generator/generator.go, internal/generator/generator_test.go, versionware/example/go.mod
Add a .Here field to scope in generator templates, so that generators
can reference files relative to where they are declared.
Drive-by: update versionware example to reference v4 properly
=> feat: generator templates can reference their location

config/linter.go, internal/linter/optic/linter.go, internal/linter/optic/linter_test.go
This is a cherry pick of #157 into v3.
Allow making very narrow exceptions for specs that do not pass optic-ci
lint rules as they currently are.
Exceptions are well, exceptional, but might need to be made to unblock
work that can't wait for rules to catch up. Exceptions are made based
on the spec file's relative path in the project, and its sha256. So any
subsequent change in the file will not fall under the exception.
=> feat: optic-ci lint exceptions

config/generator.go, go.mod, go.sum, internal/generator/functions.go, internal/generator/generator.go, internal/generator/generator_test.go, versionware/example/go.sum
Templating over the kin-openapi/openapi3 document object model is
generally powerful enough to enumerate types in various languages, as
the test in this PR demonstrates for Typescript.
However, it's inevitable that such templates will need language-specific
adaptation functions. Rather than try to include all those batteries in
the provided builtin template functions, this PR adds support for
generator function extension with Javascript.
Note that goja is the same embedded JS engine used by Grafana k6.
=> feat: custom generator functions in JS, test component templating

collator.go, internal/cmd/compiler_test.go, internal/linter/optic/linter_test.go, testdata/conflict-components/_examples/2021-06-01/spec.yaml, testdata/conflict-components/projects/2021-06-04/spec.yaml, testdata/output/2021-06-01~experimental/spec.json, testdata/output/2021-06-01~experimental/spec.yaml, testdata/output/2021-06-04~experimental/spec.json, testdata/output/2021-06-04~experimental/spec.yaml, testdata/output/2021-06-07~experimental/spec.json, testdata/output/2021-06-07~experimental/spec.yaml, testdata/output/2021-06-13~beta/spec.json, testdata/output/2021-06-13~beta/spec.yaml, testdata/output/2021-06-13~experimental/spec.json, testdata/output/2021-06-13~experimental/spec.yaml, testdata/output/2021-08-20~beta/spec.json, testdata/output/2021-08-20~beta/spec.yaml, testdata/output/2021-08-20~experimental/spec.json, testdata/output/2021-08-20~experimental/spec.yaml, testdata/resources/_examples/hello-world/2021-06-01/spec.yaml, testdata/resources/_examples/hello-world/2021-06-13/spec.yaml, testdata/resources/projects/2021-06-04/spec.yaml, testdata/resources/projects/2021-08-20/spec.yaml
Tags should be allowed to be duplicated among resource versions and
specs -- this is how multiple operations share a tag. This change allows
that to happen.
Tag conflict errors are returned when tags having the same name have
a different description or extensions. This prevents one resource
version from mysteriously overwriting that of another. The conflicting
files are referenced clearly in the error message.
Finally, all conflict errors found in the entire collate process are
returned. This avoids a "pulling teeth" interaction where the user fixes
one problem just to find the next one.
=> fix: tag conflicts, error reporting in collator

collator.go, go.mod, go.sum, resource.go, versionware/example/go.mod, versionware/example/go.sum
When collating multiple resource version docs into a single OpenAPI for
the entire service at that version, I found it necessary to reparse the
document to get a "clean" document structure -- otherwise the openapi3.T
"hangs" on to references and thinks it contains components that it
doesn't.
=> fix: clean references when collating resources into single version

scripts/release.bash
goreleaser 1.7.0 only builds and installs with Go 1.18, and we're still
on 1.17.
=> fix: goreleaser pin at 1.6.3

scripts/release.bash
Tag is `v1.6.3` (https://github.com/goreleaser/goreleaser/releases/tag/v1.6.3)
=> fix: goreleaser version typo

config/api.go, config/config_test.go, internal/cmd/compiler_test.go, internal/compiler/compiler.go, internal/compiler/compiler_test.go, internal/files/copy.go, internal/scaffold/scaffold.go, testdata/.vervet.yaml, testdata/output/2021-06-01~experimental/spec.json, testdata/output/2021-06-01~experimental/spec.yaml, testdata/output/2021-06-04~experimental/spec.json, testdata/output/2021-06-04~experimental/spec.yaml, testdata/output/2021-06-07~experimental/spec.json, testdata/output/2021-06-07~experimental/spec.yaml, testdata/output/2021-06-13~beta/spec.json, testdata/output/2021-06-13~beta/spec.yaml, testdata/output/2021-06-13~experimental/spec.json, testdata/output/2021-06-13~experimental/spec.yaml, testdata/output/2021-08-20~beta/spec.json, testdata/output/2021-08-20~beta/spec.yaml, testdata/output/2021-08-20~experimental/spec.json, testdata/output/2021-08-20~experimental/spec.yaml
Why?
Some services have a need to write compiled OpenAPI specs to multiple
destinations. This tends to happen in Typescript services in which we
want to write compiled OpenAPI specs to two places:
- src/**, for commiting into git and ingesting into Backstage
- dist/**, for runtime module access to compiled specs
We could just npm script this in these services, but when a project has
several APIs, this can become fragile -- you now have to keep
file-copying-scripts in sync with Vervet config. Miss something, and what
worked in local dev breaks in deployments.
To simplify this and reduce the error surface, Vervet can instead allow
declaring multiple output paths per API.
=> feat: support for multiple duplicate build output paths per API

.gitignore, default.nix, flake.lock, flake.nix, shell.nix
Nix is cool, flakes are the future, the cool future is now for this
repository. This will allow nix flake users to run the tool by using:
nix run github:snyk/vervet
This should be compatible with plain nix but I haven't tested that.
=> feat: Package application as a nix flake

generate/generate.go, internal/cmd/generate.go
To use vervet's generate functions inside other go tools, this exports
the generate function defined in `internal/cmd/generate.go` as a
function that accepts a param object and executes the code generator.
To avoid duplication, the generate command is updated to set up the
params from the cli options and then uses the new generate package to do
the actual generation.
=> feat: exports generate code

internal/backstage/backstage.go, internal/backstage/backstage_test.go, testdata/catalog-vervet-apis.yaml
A few fixes needed in order to generate API entities that Backstage will
accept:
- API metadata name must match ([A-Z][a-z][0-9]_-)+
- Annotations cannot nest, only one level supported.
Added a more readable, user-friendly title.
Version information is placed under labels.
Tags are also added, derived from versioning fields.
=> fix: Backstage API entity compatibility

internal/backstage/backstage.go, internal/backstage/backstage_test.go, testdata/catalog-vervet-apis.yaml
The tilde `~` in version strings seem to cause problems for our
Backstage ingest of API entities, and the `api.snyk.io/version` label is
redundant, (same info is in version-date and version-stability) so it is removed.
The error we see in Backstage:
```
{"error":{"name":"Error","message":"InputError: Policy check failed; caused by Error: \"labels.api.snyk.io/version\" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by any of [-_.], at most 63 characters in total but found \"2021-08-13~experimental\". To learn more about catalog file format, visit: https://github.com/backstage/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md","level":"error","service":"backstage","stack":"Error: InputError: Policy check failed; caused by …
```
=> fix: backstage API: remove version label, tilde from title

config/generator.go, generate/generate.go, generate/generate_test.go, internal/cmd/generate.go, internal/generator/generator.go, internal/generator/generator_test.go
rest-go-generate uses vervet's generator code to produce code for go
projects. To create a single binary, the generators.yaml and template
files for rest-go-generate are provided with embed.FS
To avoid special casing, vervet now always loads generation files from
an fs.FS object, using os.DirFS mounted at root if no other option is
provided.
=> feat: use fs.FS for generators

vervet-underground/internal/scraper/scraper.go, vervet-underground/internal/scraper/scraper_test.go, vervet-underground/server.go
We are not actually collating specs from services. Need to debug
https://github.com/snyk/vervet/blob/main/vervet-underground/internal/storage/collator.go#L63
We're failing every time
=> chore: testing collator validation missing actual collation

vervet-underground/config.default.json, vervet-underground/docker-compose.yml, vervet-underground/grafana/dashboards/dashboard.json, vervet-underground/grafana/dashboards/dashboard.yaml, vervet-underground/grafana/datasources/datasource.yaml, vervet-underground/prometheus/prometheus.yaml
This PR adds a simple dashboard and prometheus to VU's docker-compose file.  Will require #186 to browse metrics, but can be merged independently.
=> chore: add local prometheus and grafana

vervet-underground/config/config.go, vervet-underground/internal/storage/s3/client.go, vervet-underground/server.go
During testing, we found Roles were not automatically assumed from Kubernetes and had to be specified for the s3 client.
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials/stscreds#hdr-Assume_Role
```json
{"level":"info","time":1651520340,"message":"services: [https://api.deploy-system/rest]"}
{"level":"error","error":"operation error S3: ListBuckets, https response error StatusCode: 400, RequestID: TQK0VNDP7FV2PAJV, HostID: {SCRUBBED_CODE}, api error AuthorizationHeaderMalformed: The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential.","time":1651520340,"message":"failed to call service: S3, operation: ListBuckets, error: https response error StatusCode: 400, RequestID: {SCRUBBED_CODE}, HostID: {SCRUBBED_CODE}, api error …
```
=> fix: enable config to pass role arn

.gitignore, vervet-underground/internal/storage/gcs/client.go, vervet-underground/internal/storage/mem/mem.go, vervet-underground/internal/storage/mem/mem_test.go, vervet-underground/internal/storage/s3/client.go
This was a miss that prevents the /openapi/experimental lookup
on VU for all storage backends. Required for shared routing
https://github.com/snyk/gloo-edge-api-gateway/pull/374
=> fix: enable resolve on collated versions

vervet-underground/config/config.go, vervet-underground/internal/storage/s3/client.go, vervet-underground/server.go
We don't need STS when in fact AWS Supports Role based environments for bare metal and EKS.
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html
=> chore: revert sts rotating credentials

vervet-underground/internal/storage/s3/client.go, vervet-underground/internal/storage/s3/client_test.go
Found two bugs:
* we didn't correctly return on successful `HeadBucket` requests
* we didn't gracefully fail on 404 NotFound: NoSuchKey `GetObject` requests.
This has been successfully proven in pre-prod environment
=> Fix: Handle success  on bucket found calls and fix idempotent get noise

default.nix, flake.nix
proxyVendor was set which assumes that the go dependencies are available
in the building systems nix store, which is rarely the case. This patch
allows nix to download the dependencies when the requested package is
being built.
We also set the version to the last modified date so this flake will get
a new version number without having to update the version number
manually.
=> fix: Allow nix package to be build on clean systems

remove_elements.go, remove_elements_test.go, testdata/output/2021-08-20~experimental/spec.json, testdata/output/2021-08-20~experimental/spec.yaml, testdata/resource-rules.yaml, testdata/resources/projects/2021-08-20/spec.yaml, vervet-underground/internal/scraper/scraper.go
This will be used in Vervet Underground configuration to filter out
internal edge-proxy and API gateway elements from the public OpenAPI it
serves up.
=> feat: remove elements matching an exclude pattern

generate/generate.go, generate/generate_test.go, internal/generator/generator.go
This leaves generate.Generate open to extension with template functions
developed in Go.
Javascript template functions with the same name will take precedence
over Go functions provided through generate.GeneratorParams.
Built-in internal generator functions take precedence over both.
=> feat: allow extending generate templates with Go functions

vervet-underground/config/config.go, vervet-underground/config/config_test.go, vervet-underground/go.mod, vervet-underground/go.sum, vervet-underground/internal/storage/collator.go, vervet-underground/internal/storage/collator_test.go, vervet-underground/internal/storage/gcs/client.go, vervet-underground/internal/storage/mem/mem.go, vervet-underground/internal/storage/s3/client.go, vervet-underground/server.go
This allows configuring Vervet Underground to remove elements matching
certain patterns from the collated OpenAPI output.
=> feat: exclude elements matching patterns from VU output

document.go
This adds a new Document constructor which is needed by
vervet-underground when creating Documents for collation.
The private path and url fields are used to indicate the identity of
documents in errors, necessary for logging problems with that service.
To be followed by a VU change to use the new constructor.
=> fix: support instantiating a Document with an already loaded URL

vervet-underground/Dockerfile, vervet-underground/go.mod, vervet-underground/go.sum, vervet-underground/internal/storage/collator.go, vervet-underground/internal/storage/s3/client.go
Update vervet to latest version to better log collate errors by
identifying the documents which failed to merge.
Fix a panic in the s3 client that can occur when the client fails to
connect. Found this when trying to get localstack to work.
Fix inappropriate openapi3.Loader reuse among multiple documents. The
loader is very stateful and hangs on to references. This can be the
source of hard to isolate and debug problems in collate. It's possible
(though unknowable at this point) that this may clear up strange
conflicts that shouldn't be occuring in a live deployment with the GCS
backend.
=> fix: improve logging, fix s3 crash and inappropriate loader reuse

vervet-underground/config/config.go, vervet-underground/config/config_test.go, vervet-underground/internal/scraper/gcs_scraper_test.go, vervet-underground/internal/scraper/s3_scraper_test.go, vervet-underground/internal/scraper/scraper.go, vervet-underground/internal/scraper/scraper_test.go, vervet-underground/internal/storage/collator.go, vervet-underground/internal/storage/collator_test.go, vervet-underground/server.go
Two fixes:
- Separate the service name from the URL, so that endpoints can be
updated without breaking historical continuity.
- Ignore /openapi endpoints during collation, if we've already merged
these paths into the result.
=> fix: separate service name from URL, collate around openapi paths

vervet-underground/config/config.go, vervet-underground/internal/scraper/scraper.go, vervet-underground/internal/storage/gcs/client.go, vervet-underground/internal/storage/gcs/client_test.go, vervet-underground/internal/storage/mem/mem.go, vervet-underground/internal/storage/mem/mem_test.go, vervet-underground/internal/storage/s3/client.go, vervet-underground/internal/storage/s3/client_test.go, vervet-underground/internal/storage/storage.go, vervet-underground/internal/storage/testing.go
Previously vervet underground storage.Storage would collate versions
from all stored services, even if those services had been removed from
the configuration (e.g. because they were sunsetted).
Config now provides a ServiceFilter method which gets a filter of
current service names that is used in CollateVersions to remove any
versions from services *not* in the config, so old services are not
returned as part of the final openapi spec.
=> fix: CollateVersions filters out old services

collator.go, merge.go, merge_test.go, testdata/merge_test_dst.yaml, testdata/merge_test_src.yaml
This PR implements appropriate merge of top-level OpenAPI extensions.
`x-snyk-api-stability` seems to be a special extension that needs to be removed from the merge for the tests to pass. I'd like to get some more eyes on this.
=> fix: merge top-level OpenAPI extensions

vervet-underground/internal/storage/collator.go, vervet-underground/internal/storage/collator_test.go
Allow tags to conflict when collating multiple services and let the last write win.
@migruealt This configures VU to use the StrictTags collate option we created -- we were really close to getting VU to work last week!
=> fix: collate OpenAPI specifications without strict tag merging

vervet-underground/server.go
This should fix the `text/plain` content type we were getting from VU
responses. In Go net/http, headers need to be set before writing them to
the response writer with `WriteStatus`, or they won't show up in the
response.
=> fix(VU): write response header after setting content-type

vervet-underground/go.mod, vervet-underground/go.sum, vervet-underground/internal/handler/handler.go, vervet-underground/internal/handler/handler_test.go, vervet-underground/server.go
Strip trailing slashes from requests using chi middleware to be more
tolerant of user requests.
Drive-by, upgrade chi to v5 (current major release).
=> fix(vu): strip trailing slashes from requests, use chi v5

collator.go, collator_test.go, inliner.go, testdata/conflict/_examples/2021-06-15/spec.yaml, testdata/conflict/_examples2/2021-06-15/spec.yaml
Option to use the first path info declared for a given route, ignoring
subsequent route duplicates. This mimics routing table behavior, where
ordering is significant and the first match is used. Default behavior is
to fail the collate on a conflict error if multiple paths share the same
route.
Intended use case is deterministic path resolving among services
aggregated by vervet underground.
Route equivalence ignores path parameter names; only parameter path
positions are considered. Astute readers will note this change also
resolves a subtle bug in which vervet could have produced an OpenAPI
result containing distinct paths which were not acutally distinct
routes.
Drive-by: move Inliner and RefRemover to a separate source file.
=> feat: collate option to use the first route

remove_elements.go, remove_elements_test.go
Add support to RemoveElements for removing paths.
This capability will be used for configurable path blocklists in vervet
underground.
=> feat: support for excluding paths when removing elements

vervet-underground/go.mod, vervet-underground/go.sum
This enables recently landed features:
- first-path-wins collation
- overlay support
- path exclusion
=> fix(vu): update VU vervet dependency to latest

vervet-underground/go.mod, vervet-underground/go.sum, vervet-underground/internal/storage/collator.go, vervet-underground/internal/storage/collator_test.go
VU wasn't using the new collate option we added -- this updates VU to
use the first instance of a path found when collating OpenAPI among all
services.
Added test coverage.
=> fix(vu): use the UseFirstRoute collate option in VU collate

default.nix
At some point the go dependencies were changed which changed the hash,
nix will not build unless the hash matches so it can guarantee
reproducibility.
=> chore: update nix dependencies hash

version.go, version_test.go
Allow external manipulation of the reference time used to calculate
lifecycle TTL expirations with an optional environment variable.
VERVET_LIFECYCLE_AT may be set to control this reference time when
running vervet. This allows for manual control over when lifecycle TTL
changes affect compiled OpenAPI files.
=> feat: specify lifecycle reference time in environment variable

inliner.go, remove_elements.go
When traversing the OpenAPI document object model with reflectwalk, check whether a `reflect.Value` may be accessed with `CanInterface()` before accessing it to avoid an unexpected panic.
Fixes #241
=> fix: filter out unexported values when using reflectwalk

export_test.go, version.go, version_test.go
Separates the lifecycle date into two dates used for deprecation and release.
- For determining deprecation we use the `VERVET_LIFECYCLE_AT` env var, and if not set default to the current date.
- For determining whether a version is unreleased we always use the current date
=> fix: separated the lifecycle date into deprecation and release

vervet-underground/internal/storage/revision.go, vervet-underground/internal/storage/revision_test.go
The rules for resolving versions across services to collate a SaaS is slightly different from resolving versions across resources to collate a service.
vervet.VersionSlice.Resolve will resolve the greatest effective stability on a version date, which is appropriate for API consumers and collating within a service. This works because a given resource may only have one release on a given day, due to the way OpenAPI specs are organized into per-day folders.
At the SaaS level, each service may have concurrent stability versions active at each version date. Therefore when resolving the latest version, the stability searched for should be matched exactly rather than used as a lower bound for a range search.
=> fix(vu): match stability when resolving latest revision of version

export_test.go, resource.go, resource_test.go, spec.go, spec_test.go, version.go, version_test.go, versionware/handler.go, versionware/validator.go, versionware/validator_resolve_test.go
Related to snyk/vervet#248, a similar stability version issue affects
validation middleware "versionware".
This breaking change replaces VersionSlice.Resolve with
VersionIndex.Resolve.
It turns out resolving versions correctly across date and stability
requires tracking the most recent release per stability for each
distinct version date. This requires a different structure for indexing;
a simple []Version slice does not suffice for an O(logN) search
complexity.
Fixes #250.
=> fix: resolve OpenAPI validators at the correct stability level

internal/cmd/compiler.go, internal/compiler/compiler.go, internal/compiler/compiler_test.go
When lint flag is set to false, the lint configuration is still parsed and vetted. In the case of sweater-comb configured with the original branch, this causes an issue when the .git directory is not there, for instance when building in Docker ignoring .git dir, terminating the command execution.
This change removes totally linters configuration when lint flag is set to false.
=> fix: disable lint config parsing when lint disabled

internal/cmd/backstage.go
We need to make sure that we always produce a reproducible output when generating catalog-info.yaml, it should be a pure function of the vervet config and open api specs.
We are unmarshalling the vervet config into a go map then iterating over that. Go randomises the order of values in a map so if a project declares multiple apis in a vervet config then the order of the resulting api objects in the catalog-info would be random. The only way to get stability is to use an external ordered structure, in this case we can use a string slice of the keys.
=> fix: make order of apis in generated catalog-info stable

default.nix
This hash is used by nix to ensure reproducible builds. It is calculated from all of the dependencies defined in go.sum, therefore it needs updating whenever a go dependency changes - this has happened since this hash was last updated.
=> fix: update nix flake dependencies hash

.github/CODEOWNERS
Moving to Access as Elk is disbanding
=> chore: change codeowners to Access

scripts/dist.bash, vervet-underground/Makefile
Disables dynamic linking (CGO_ENABLED=0) when building vervet binaries in CI to remove linking issues in the OS the binaries are executed.
=> fix(build): disable dynamic linking by setting CGO_ENABLED=0

merge.go, merge_test.go, testdata/merge_test_dst.yaml, testdata/merge_test_src.yaml
PR #269 introduces a bug with the upgrade of kin-openapi. Component extensions are not correctly identified and considered as part of merging specs. However, a nil pointer exception can occur when no extensions are specified as part of a spec.
This PR correctly handles this nil pointer and add tests to validate behaviour.
=> fix: component extension merge

merge.go, merge_test.go, testdata/merge_test_dst.yaml, testdata/merge_test_src.yaml, versionware/example/releases/embed.go
Before bumping kin-openapi, component extensions were not actually
merged, even if the tests pretend they were.
After bumping kin-openapi, I've added the behaviour of merging component
extensions which was a mistake as it modifies the behaviour of component
generation.
This is reverting this behaviour.
=> fix: stop merging component extensions

vervet-underground/internal/scraper/scraper.go
We are seeing the scraping service time out during its initial scrape with no indication about what is causing it. This should help identify the slow services.
=> chore: log messages when starting/finishing scraping services

flake.nix, shell.nix, spectral.nix
Spectral-cli is required to run some tests so it needs to be available in a dev environment.
Since it is not available in nixpkgs, a simple build is provided that pulls in all of its dependencies.
=> chore: add spectral-cli to nix devshell

collator_test.go, internal/cmd/compiler_test.go, testdata/competing-specs/projects/2021-08-20/spec.yaml, testdata/competing-specs/special_projects/2023-03-13/spec.yaml, vervet-underground/internal/storage/collator_test.go, vervet-underground/internal/storage/revision.go
If an endpoint is moved from one service to another, then there is a chance that we will continue to use the path from the old service even though the newer one has a more recent version.
It is assumed that all services are independent when doing version resolution, then all the services are merged together. This is fine if the services do not have overlapping paths but will cause unexpected behaviour otherwise.
We keep the first spec for each endpoint we find when collating versions, which means we need to find the most recent version first. To do this we can change the order we process specs by using the vervet version before the scrape timestamp - which will mean more recent versions will be processed first.
=> fix: pick newer versions of endpoints when collating over services

vervet-underground/internal/scraper/scraper.go
Add an error log when an error is encountered scraping a service. Currently the errors are accumulated and logged at the end with no identifying info.
=> fix: log scrape errors for services

.gitignore, vervet-underground/internal/scraper/scraper.go, vervet-underground/internal/scraper/scraper_test.go
This change will enable the use of legacy APIs using a default version `2021-01-01` (which predates `vervet`) without `vervet-underground` scraping for the OpenAPI contract. This enables `vervet` to be used on legacy APIs which do not meet the OpenAPI standard.
To test to end to end:
- Run a service locally with an API using the default version `2021-01-01`.
- Used a `config.local.json` file to point to that service.
- Started `vervet-underground` after updating the `docker-compose.yml` and `server.go` to point to the `config.local.json` file
- Called `http://localhost:8080/openapi` confirm the default version is missing from the response.
=> feat: skip saving legacy version when running scrapper

.circleci/config.yml, Makefile, go.mod
Keeping up with the go version, updating the Vervet go version to 1.20. Next will be updating the `vervet-underground`.
Add phony tidy target to the makefile to run `go mod tidy -v` for ease of use.
=> chore: update go version to 1.20 for vervet

.circleci/config.yml, .gitignore, Makefile, vervet-underground/.golangci.yml, vervet-underground/Dockerfile, vervet-underground/Makefile, vervet-underground/go.mod, vervet-underground/internal/storage/gcs/testing/testing.go
- Update the vervet underground go and `golangci-lint` versions to match that of `vervet` to ensure a consistent experience.
- Update the `vervet undergound` `makefile` to install `golangci-lint` in the local bin, enabling us to work on `vervet underground` independently. It also replicates the setup of `vervet`.
- Update docker and ci config files to use the correct version of go and `golangci-lint`.
=> chore: consistent go and golangci-lint versions for both vervet and VU

vervet-underground/Dockerfile
As part of the 'rollout base images' fanout - https://docs.google.com/document/d/1I-vxsuHlmBlM8JHSDpvOmVMGeQQcbPgb8jH1ELEE9wo/edit
=> chore: secure base image

.circleci/config.yml, vervet-underground/Dockerfile
The previous commit which introduced the new secure base image broke the deploy pipeline. This should hopefully fix it.
=> chore: fixes a deploy issue

.circleci/config.yml, vervet-underground/Dockerfile
Due to other changes, the build phase needed the DOCKER_BUILDKIT env variable.
=> chore: deployment fixes

.circleci/config.yml, testdata/catalog-vervet-apis.yaml, testdata/output/2023-06-01~experimental/spec.json, testdata/output/2023-06-01~experimental/spec.yaml, testdata/output/2023-06-02~experimental/spec.json, testdata/output/2023-06-02~experimental/spec.yaml, testdata/output/2023-06-03~experimental/spec.json, testdata/output/2023-06-03~experimental/spec.yaml, vervet-underground/Makefile
This PR updates publishing of vervet-underground to use Snyk's internal publish orb.
This ensures that the container image gets scanned.
=> feat: add publish orb for vu

go.mod, go.sum, resource.go, spec.go, version.go, versionware/example/go.mod, versionware/example/go.sum
Provides a Versions method on the VersionIndex type which returns a copy of the VersionSlice used to build the index.
This is a pre-requisite to upgrade the vervet version of vervet-underground.
=> fix: provide a Versions method on VersionIndex

default.nix, flake.lock, flake.nix, shell.nix
Main change is updating the dependencies hash so it is up to date with the most recent changes.
Additionally the devshell has been updated to use the latest node LTS and match the go version defined in go.mod, which required an update to nixpkgs.
=> fix: update nix flake after dependency upgrade

vervet-underground/config/config.go
When running this service we may want to inject config variables that aren't statically defined in a config file. Env vars are an ideal way to do this.
=> feat: allow loading config vars from env

collator.go, collator_test.go, testdata/conflict-components/_examples/2021-06-01/spec.yaml, testdata/conflict-components/projects/2021-06-04/spec.yaml
When collating schemas from multiple services, it is very likely that components with the same name will be defined in several places. We use a comparison function to detect when this is the case and inline components if they have already been declared.
This comparison function however ignored fields meant for documenting fields. Which is fine when it was written as the only concern was generating openapi specs inner service to validate requests. However now we are using the collated specs to generate documentation, this behaviour is very surprising. Especially when the description is context sensitive.
This will increase the size of our specs slightly, it should not be that significant. It will require us to recompile our existing specs to fix the broken versions.
=> fix: prevent similar components from being overwritten

README.md, mkdocs.yml, versionware/example/chi/example_test.go, versionware/example/embed_test.go, versionware/example/go.mod, versionware/example/go.sum, versionware/example/gorilla/example_test.go, versionware/example/resources/things/2021-11-01/handlers.go, versionware/example/resources/things/2021-11-08/handlers.go, versionware/example/resources/things/2021-11-20/handlers.go, versionware/example/resources/things/types.go, vervet-underground/config/config.go, vervet-underground/config/config_test.go, vervet-underground/go.mod, vervet-underground/go.sum, vervet-underground/internal/handler/handler.go, vervet-underground/internal/handler/handler_test.go, vervet-underground/internal/scraper/scraper.go, vervet-underground/internal/storage/collator.go, vervet-underground/internal/storage/collator_test.go, vervet-underground/internal/storage/gcs/client.go, vervet-underground/internal/storage/mem/mem.go, vervet-underground/internal/storage/revision.go, vervet-underground/internal/storage/revision_test.go, vervet-underground/internal/storage/s3/client.go, vervet-underground/internal/storage/storage.go
There are multiple modules in this repo that depend on each other by external package names. As such we could not update them all at once until the main package was released. That has now happened so we can update all the other references.
=> feat: update auxiliary modules to use vervet v6

export_test.go, resource.go, version.go, versionware/handler.go, versionware/handler_test.go
When compiling specs we always show the highest stability level for a given version of an endpoint. As such we need to use the same logic when resolving handlers for dealing with that endpoint.
Before this patch it is possible that a request for a beta version will hit the handler for the beta endpoint, but then the request would be validated for the GA version of the same endpoint causing the request to fail.
This aligns endpoint behaviour with what we publicly document for a specific version.
=> fix: resolve highest stability from versionware

default.nix, flake.lock
Dependencies have been updated since the last time we updated the flake so it no longer builds, this resyncs them.
Might as well update inputs at the same time.
=> chore: update nix flake

vervet-underground/Dockerfile
Use Snyk Node base images version [2.3.1_202403150706](https://github.com/snyk/snyk-base-images/releases/tag/2.3.1_202403150706) to pickup security fixes. See [PRODSEC-1765](https://snyksec.atlassian.net/browse/PRODSEC-1765) for details.
-- 
Snyk ProdSec
[PRODSEC-1765]: https://snyksec.atlassian.net/browse/PRODSEC-1765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update Snyk Node base images

collator.go, internal/compiler/compiler.go, merge.go, merge_test.go, spec.go, testdata/merge_test_conflict.yaml
When we roll up versions and copy over paths from older spec, we naïvely merge the components defined in those specs. This is a problem when similar named components are defined in two versions of a spec that is rolled up.
To fix this problem is a lot of effort which we do not have time for right now, but detecting it is relatively easy. This patch will fail building specs if we detect such a case so a user can work around it manually.
=> fix: throw error when conflicting components are found

vervet-underground/Dockerfile
Updates the snyk base image to the latest released version for security updates. See [PRODSEC-1788](https://snyksec.atlassian.net/browse/PRODSEC-1788) for details.
Released on Friday April 19, 2024 at 08:58 (UTC)
- **ubuntu-20-node-18**: Upgrade Node-18 base image to NodeJS version [18.20.2](https://nodejs.org/en/blog/release/v18.20.2)
- **ubuntu-20-node-20**: Upgrade Node-20 base image to NodeJS version [20.12.2](https://nodejs.org/en/blog/release/v20.12.2)
**Full Changelog**: https://github.com/snyk/snyk-base-images/compare/2.3.6_202404171800...2.3.7_202404190856
-- 
Snyk ProdSec
[PRODSEC-1788]: https://snyksec.atlassian.net/browse/PRODSEC-1788?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update Snyk base images [PRODSEC-1788]

vervet-underground/Dockerfile
We run the same container image for the api and scraper, so we actually need the scraper binary in that image. Previous patch built it in the build stage but forgot to copy it to the final image.
=> fix: add scraper to VU container image

internal/compiler/compiler.go, version.go, version_test.go
Previously we paniced with the message:
panic: invalid lifecycle (1)
which is not helpful and doesn't give any indication about what went wrong or how to fix it.
This new error message should be a lot clearer and help users to realise their mistake.
I see no reason why we have to panic when we get an unreleased version, so that has been removed.
=> fix: report better error when building future versions

collator.go, collator_test.go, internal/scraper/gcs_scraper_test.go, internal/scraper/s3_scraper_test.go, internal/scraper/scraper_test.go, testdata/operation-change/_examples/2021-06-15/spec.yaml, testdata/operation-change/_examples2/2021-06-15/spec.yaml
We were previously overriding whole paths if they were defined in a newer version. This means that operations are marked as sunset if they are not redefined in the newer spec. This is surprising behaviour.
This patch will mean that we merge all operations, so future versions do not need to redeclare operations on each path for them to remain current.
Running against this latest version will rewrite already generated specs.
=> fix: merge operations from duplicate paths

internal/cmd/cmd.go, internal/cmd/compiler.go, internal/compiler/compiler.go, internal/compiler/compiler_test.go, internal/simplebuild/build.go, internal/simplebuild/build_test.go, internal/simplebuild/output.go, internal/simplebuild/output_test.go
- if the pivot date is in the future, does not generate a simplebuild
- add a "synthetic" version at the pivot date
- if the pivot date is in the past, still generates "synthetic" version at the pivot date
=> feat: change build to be a meta-build command, invoking old and simple build

.circleci/config.yml
This PR attempts to upgrade the go version of circle-ci to 1.22.5 in order to allow newer versions of dependencies.
=> chore: upgrade go to 1.22.5 in circle-ci

Dockerfile
This PR attempts to upgrade the go version used within the Dockerfile during the build process
=> chore: upgrade go within dockerfile

internal/cmd/compiler.go, internal/simplebuild/build.go, internal/simplebuild/build_test.go
This PR attempts to add a check during simple build to ensure that resources which have only one version (new resources since simplebuild is only run after the pivot date) are versioned using the latest release of the global API ensuring they do not end up creating a new version of the global API
=> feat: single-version-resources to be before latest version

internal/simplebuild/build.go, internal/simplebuild/build_test.go, resource.go
This PR attempts to annotate the operations added during the new build process with the x-stability-level and x-snyk-api-stability annotations. These annotations are meant for the client to be able to tell which stability the requested path is at.
=> feat: annotate operations with stability level

internal/simplebuild/build.go, internal/simplebuild/build_test.go
context: 
the x-stability-level values dont map directly to vervet stability levels; this PR maps "ga" to "stable"
If we dont fix this, tools like oas-diff start failing the generated spec
=> fix: map x-stability value to a parsable value

internal/simplebuild/build.go, internal/simplebuild/build_test.go
context: https://snyk.slack.com/archives/C01HY16GZTR/p1728475585279769
need to filter out experimental and wip versions from the single spec
=> fix: filters out wip versions from simplebuild collation

internal/simplebuild/build.go, internal/simplebuild/build_test.go
- existing build implementation copies over the first server block from the spec, carry over the behaviour
=> fix: populate the servers block for simple build

document.go, document_test.go
Previously we were reading the document version from the top level x-snyk-api-version extension. This extension does not exist on documents past the pivot date as versions are done per endpoint. This resulted in all backstage commands failing. (eg vervet backstage update-catalog)
This information is available in the file path, so instead of poluting our new documents with this extension we can read it from there instead. This change is backwards compatable with older specs.
=> fix: get document version from filename to fix backstage cmds

internal/openapiwalker/walker.go, internal/openapiwalker/walker_test.go
- although we are enforcing additional properties `= false` going forward there are a few existing repos which use additional properties
=> fix: openapi walker walks into additional properties

internal/cmd/backstage.go, internal/cmd/compiler.go, version.go, version_test.go, versionware/handler.go, versionware/handler_test.go
- fixes resolution for beta endpoints, post pivot date
- beta endpoints are now folded into the GA spec
- not resolving `beta` and `experimental` versions post pivot date
=> fix: update versionware to consider pivot date

internal/compiler/compiler.go, internal/compiler/compiler_test.go
- beta/experimentals should not be generated on or past the stop date
=> fix: extra versions generated on pivot date

.circleci/config.yml
Pushes to main are rightfully blocked except for deploy keys, the GH_TOKEN used was not a deploy key.
=> fix: use deploy key for pushing to main on deploy

internal/backstage/backstage.go, internal/backstage/backstage_test.go, internal/cmd/backstage.go, testdata/catalog-vervet-apis-with-pivot.yaml, testdata/catalog-vervet-apis.yaml
Backstage names need to be unique, there is nothing preventing users from
having the same name across their api specs which would be fine up until we
generate the backstage resources. To prevent us burdening developers with the
chore of renaming them, we can add the api name to the name which is guaranteed
to be unique.
This prevents the underlying issue and emits an error in case there is a different path to this error.
=> feat: prevent conflicting names in catalog-info

config/api.go, config/api_test.go, internal/cmd/backstage.go
`update-catalog` fails with a nil pointer if output is not set 
```
$ go run github.com/snyk/vervet/v8/cmd/vervet@v8.7.2 backstage update-catalog
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x1008ef650]
goroutine 1 [running]:
github.com/snyk/vervet/v8/config.(*Output).ResolvePaths(...)
/Users/jatin/go/pkg/mod/github.com/snyk/vervet/v8@v8.7.2/config/api.go:79
github.com/snyk/vervet/v8/internal/cmd.processCatalog(0x140001c1e80, {0x0, 0x0})
/Users/jatin/go/pkg/mod/github.com/snyk/vervet/v8@v8.7.2/internal/cmd/backstage.go:192 +0x4a0
github.com/snyk/vervet/v8/internal/cmd.UpdateCatalog(0x140001c1e80?)
/Users/jatin/go/pkg/mod/github.com/snyk/vervet/v8@v8.7.2/internal/cmd/backstage.go:75 +0x24 …
```
=> fix: nil check for config output

internal/cmd/cmd.go, internal/cmd/sanitize.go, internal/cmd/sanitize_test.go, internal/storage/disk/disk.go
This PR introduces a new sanitize command to remove sensitive information from versioned OpenAPI specs before distribution. 
Given a directory of compiled specs (one subfolder per version), the command loads each spec.yaml, filters out configurable extensions, headers, or entire paths, and saves the sanitized spec to a specified output directory.
```
vervet sanitize \
--compiled-path ./internal/rest/api/versions \
--out ./sanitized \
--exclude-extension '^x-internal$' \
--exclude-header '^X-Secret$' \
--exclude-path '/internal'
```
This will read all spec.yaml files under each version subfolder, remove fields matching the exclusion criteria, and write sanitized openapi.yaml files to the ./sanitized directory.
=> feat: sanitize-command

internal/backstage/backstage.go
We previously appended the stability of apis before the pivot date, this is made after the truncation to 63 characters.
Which results in invalid names if api names are too long, this truncates the name back to 63 characters
=> fix: truncate api names for old versions

internal/simplebuild/build.go, internal/simplebuild/build_test.go
This allows the build to pass if the server serving the latest global version is not available
=> fix: continue build if fetching latest version fails

remove_elements.go, remove_elements_test.go
We previously had a bug where top level extensions would still appear in the final compiled specs on the top level of the document.
This change attempts to fix that by applying the remove rules to the documents top level extensions
=> fix: remove top level extensions

clean.go, remove_elements.go, remove_elements_test.go, testdata/remove-elements.yaml
We have a process to remove elements from compiled specs to make sure we are not leaking any data. However those elements could be referencing components that we did not remove.
This patch does a final pass after elements have been removed to clean up any components that are no longer referenced.
=> fix: remove unused components after removing elements

.circleci/config.yml
Updates the release job, creating a version branch which is merged to main, allowing branch protection bypass.
=> chore: update the prepare-release job to use a branch instead of pushing main
