snyk/vervet

vervet-underground/README.md
=> docs: improve intro with why and what VU is about

vervet-underground/internal/scraper/scraper.go
Replace the WaitGroup in scraper.Run with a buffered channel.
=> chore: simplify scraper.Run

.circleci/config.yml
Missed context and using circle image instead
=> chore: fix docker image vu build

.circleci/config.yml, go.mod, go.sum, vervet-underground/docker-compose.yml, vervet-underground/go.mod, vervet-underground/go.sum
Upgrade golang dependencies and add fix for docker-compose to include config parameter by default.
=> chore: go upgrade deps

internal/cmd/generate.go, internal/generator/generator.go, internal/generator/generator_test.go
Now print a list of generated files when running `vervet generate`.
Add a `--dry-run` option to execute templates without writing output,
and get a list of files that would be generated. Useful for checking
whether there are any uncommitted changes in generated files.
=> feat: list generated files, --dry-run option

README.md
This updates the readme with some minor rewording, an updated
description of generators, and the scaffolding section removed.
=> chore: update README to reflect 4.x

.circleci/config.yml
=> chore: revert ci build-vu

vervet-underground/Makefile, vervet-underground/config.gcs.sample.json, vervet-underground/config.s3.sample.json, vervet-underground/config/config.go, vervet-underground/config/config_test.go, vervet-underground/docker-compose.yml, vervet-underground/go.mod, vervet-underground/go.sum, vervet-underground/internal/scraper/gcs_scraper_test.go, vervet-underground/internal/scraper/scraper_test.go, vervet-underground/internal/storage/gcs/client.go, vervet-underground/internal/storage/gcs/client_test.go, vervet-underground/server.go
Based on examples from google and enabling local validations:
* https://github.com/GoogleCloudPlatform/golang-samples/blob/main/storage/objects/main.go
* https://github.com/fsouza/fake-gcs-server/blob/main/examples/go/main.go
* https://github.com/fsouza/fake-gcs-server has a docker image usable for integration testing
https://snyksec.atlassian.net/browse/GRFE-513
=> feat: add support for gcs

vervet-underground/internal/storage/s3/client.go
miss from #194 required for STS credential rotations by the SDK
=> fix: actually add credentials cache is required

vervet-underground/internal/scraper/gcs_scraper_test.go, vervet-underground/internal/scraper/s3_scraper_test.go, vervet-underground/internal/scraper/scraper.go, vervet-underground/internal/scraper/scraper_test.go, vervet-underground/internal/storage/gcs/client.go, vervet-underground/internal/storage/gcs/client_test.go, vervet-underground/internal/storage/mem/mem.go, vervet-underground/internal/storage/mem/mem_test.go, vervet-underground/internal/storage/s3/client.go, vervet-underground/internal/storage/s3/client_test.go, vervet-underground/internal/storage/storage.go, vervet-underground/server.go
https://github.com/snyk/vervet/issues/198
Fixes some stylings from #197 as well
=> fix: add context propagation to VU

collator.go, collator_test.go, internal/cmd/compiler_test.go, resource.go, testdata/conflict-components/_examples/2021-06-01/spec.yaml, testdata/conflict-components/projects/2021-06-04/spec.yaml
Implements an inliner to inline the spec component when there is a conflict
=> fix: implement inliner to inline component conflicts

.circleci/config.yml
Change CCV for SVU: https://github.com/caarlos0/svu
=> chore: Change CCV tag generator for SVU

collator.go
This change introduces a StrictTags option to vervet.Collator which allows controlling whether a tags conflict causes an error or is resolved automatically. For VU the last tag with a given name wins. For the Vervet CLI, tag conflicts result in an error.
=> fix: StrictTags collator option; last tag wins in VU

go.mod, go.sum
https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXCRYPTOSSH-3026972
=> fix: bumps crypto package to patched version

go.mod, go.sum
Update golang.org/x/crypto version
=> chore: update golang.org/x/crypto version

README.md
Updates the ReadMe with some helpful information.
=> feat: add notes on release to readme

default.nix, flake.lock, shell.nix
The nix package has not been touched in a while so the dependencies were out of sync with the projects, this aligns them again so it will build.
=> fix: update nix build dependencies

catalog-info.yaml
Please update the 'type: undefined' according to the [documentation](https://snyksec.atlassian.net/wiki/spaces/PRODSEC/pages/1661075458/Asset+Classification+of+Software+Code+Repositories) and we'll review this together.
=> assets classification

default.nix, shell.nix
Just some routine updates, keep everything in sync for nix users (aka me)
=> feat: update nix flake

.circleci/config.yml
This orb has become the new standard that Snyk uses internally for all its projects.
=> chore: use prodsec snyk orb in CI/CD

.circleci/config.yml, .github/CODEOWNERS, catalog-info.yaml
- feat: update CODEOWNERS
- feat: update catalog-info
- feat: update CI with new team references and bump orbs
=> feat: re-org changes

internal/compiler/compiler.go, internal/storage/collator.go
Updates sunset header with the correct description as per implementation
=> fix: update sunset header

internal/cmd/compiler.go
This PR changes the pivot date for introducing the simple build flow for new specs.
=> feat: change pivot date to october first

.circleci/config.yml
- enables publishing a version when fixes are made to the v7 branch
=> fix: add v7 as another main branch

go.mod, internal/openapiwalker/walker.go, internal/openapiwalker/walker_test.go
- sorts map keys in reflect walker, for more stable generation results
=> fix: improve stability of generation by sorting keys

README.md
This PR attempts to document the way vervet works past the pivot date with the new simplified versioning strategy.
=> chore: simplified versioning documentation

internal/scraper/scraper.go
Most services are built without support for serving a HEAD request to their openapi endpoints. Currently we fall back to the normal GET path if the service returns method not supported.
It would take a lot of effort to update each service to support handling HEAD requests, for not much benefit. The normal GET path is fast enough without having this fast path.
Having this path is just making noise in metrics for people logging client errors.
=> feat: remove HEAD fast path for scraper

.circleci/config.yml, Dockerfile, Makefile
[EXT-2760]
[EXT-2760]: https://snyksec.atlassian.net/browse/EXT-2760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: move to gar/stigs images

.circleci/config.yml
Changes the ssh fingerprint to fix the version release pipeline
=> fix: use team-api machine user ssh key
